apiVersion: v1
kind: PersistentVolume
metadata:
  name: image-registry-pv
  namespace: openshift-image-registry
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  nfs:
    path: /registry
    server: 172.16.1.5
  persistentVolumeReclaimPolicy: Retain
